### ISSUE TITLE
Update the DX documents with the latest Syncromatics.Engineering.DX.Common template

### ISSUE THREAD

**Issue by thzinc** [syncromatics/XamarinUsbDriver#1]
# Overview

This project is lacking a README, license, contributor's guide, and a code of conduct.

A brief description of this project is:
> This is a .NET library to interact with Syncromatics' USB devices through Xamarin

# Implementation notes

* [Ensure the Syncromatics.Engineering.DX.Common template is installed](https://github.com/syncromatics/Syncromatics.Engineering.DX.Common#quickstart)
* In the root of the project folder, run `dotnet new syncdx-common --force --projectName TheActualProjectName --githubRepo TheActualGithubRepoName --nugetPackage TheActualNugetPackageName`
* Edit the `README.md` file to include the bits that are relevant to this project.

**Comment by MacNcheeese** [comment]
In Progress

**Comment by thzinc** [comment]
Thanks @MacNcheeese!
